### ISSUE TITLE
Rewrite gsoc patch collector as Python

### ISSUE THREAD

**Issue by jayvdb** [coala/meta#124]
This is used by students to do submissions:

https://github.com/sils/configurations/blob/master/scripts/git/collect_authors_patches.sh

@MacBox7 reported problems using it.

Anyway, we can build it in Python.

**Comment by jayvdb** [comment]
This could be a tool we dump in https://github.com/summerofcode/ , before or after it is rewritten.

**Comment by naveenkumarsangi** [comment]
@jayvdb, I had problems using it last year as well. Only that I didn't report things, my bad.

**Comment by srivama** [comment]
Please assign this to me.

**Comment by naveenkumarsangi** [comment]
There you go @srivama. Feel free to proceed.

**Comment by srivama** [comment]
@nkprince007  Thanks :smile:. Should I add the new file in the gsoc-orgs directory mentioned above or here in meta itself?

**Comment by naveenkumarsangi** [comment]
Probably just here. We can migrate things later.

**Comment by srivama** [comment]
@jayvdb You can close this issue ;)
