### ISSUE TITLE
Info Mail

### ISSUE THREAD

**Issue by sims1253** [coala/meta#19]
Our host at linuxwochen suggested that we should create an info mail that is a short introduction to what coala is. He would like to ping some people in the professional software development scene about us but need something he can show.

Clarification:
The idea is to have something a professional can be shown to see what coala does without all the "its like spell checking for code" stuff we do at conferences. As little "coala is the best thing since green tea"-in your face working and ideally it could have a nice layout and maybe some graphics.

**Comment by sils1297** [comment]
Sounds awesome, you got the contact details? (No need to publish here but somebody should have it, as this issue is not confidential.)

**Comment by sims1253** [comment]
He said he would send it to them if we gave something to him. I think this would be better because he knows the people and would suggest us. Having an info mail is useful in general.

**Comment by sims1253** [comment]
To make this clear again (also put an edit in the description)
This is about having something to present coala to professionals in the software development world.

**Comment by sims1253** [comment]
@Uran198 @Adrianzatreanu

**Comment by Uran198** [comment]
I think what will be useful for professionals to know about coala is:
- A few most useful commands to get started fast. They may be busy people and have no time to go through tutorial
- Clarification on what tasks can get parallazied and what not. The concept of sections.
- Clear dependencies for each bear (I'm not sure we have it).
- Promotionals:
  - common interface
  - different output format support
  - performance win (would be very helpful to include some study in environment that can be easily reproduced)

I think the most useful thing is the common interface, so it may be good to accent that.

**Comment by Uran198** [comment]
Also, to create a flyer we can use one of the free online services.

**Comment by sims1253** [comment]
@Adrianzatreanu anything you can add?

**Comment by Adrianzatreanu** [comment]
i think we can point out how coala does a great job at explaining you what is wrong when an analysis is found.

also the auto-applying by setting it to auto-apply saves a LOT of time, might be good to have this shown? like u dont need to click 100 times if you know you need to change stuff.

**Comment by Adrianzatreanu** [comment]
so:

- detailed analysis on errors
- amazing auto-fixing feature for all your code

**Comment by sils1297** [comment]
writing one at https://etherpad.gnome.org/p/coalaforswdevs

**Comment by sils1297** [comment]
writing a formatted version now at https://docs.google.com/document/d/1dOVZDpEqLaZJEkntiCXVHqXxvaFNai-whnR7Q2PUz5A/edit?usp=sharing

**Comment by jayvdb** [comment]
Is this needed any more?

**Comment by sils** [comment]
no
