### ISSUE TITLE
For the love of god get rid of the weekly comment spam on inactive PRs

### ISSUE THREAD

**Issue by underyx** [coala/meta#82]
I have over a hundred emails which are just these comments. I keep having to unsubscribe from discussions to avoid all the notifications on PRs I'm interested in that are inactive. It also pollutes the comment thread with a tower of useless crap messages.

**Comment by jayvdb** [comment]
I believe this will be solved by gitmate-2, which is very close to being 'good enough' to replace gitmate.

**Comment by sils** [comment]
@underyx we're starting to use gitmate-2 and phasing out gitmate-1. The weekly spam should reduce until it's gone right now :)

**Comment by underyx** [comment]
Is it not easy to just turn it off, though?

**Comment by nkprince007** [comment]
Comment spam is now gone with gitmate-2
