### ISSUE TITLE
Add algolia docsearch to docs

### ISSUE THREAD

**Issue by meetmangukiya** [coala/meta#91]
Current search is simple keyword search. Algolia docsearch does a pretty good job in searching documentations. It is being used at docs.gitlab.com if you are looking for an example

**Comment by meetmangukiya** [comment]
1. DocSearch is almost instantaneous and way faster than the one offered by sphinx by default.
2. DocSearch provides auto-completion on search.
3. It provides live searching.

**Comment by yukiisbored** [comment]
Will it work even without javascript?

**Comment by meetmangukiya** [comment]
No, it most probably uses AJAX for live searching, else it wont work

**Comment by hemangsk** [comment]
Live search is definitely good. There is also Mkdocs, used for GitMate documentation, which has a similar feature, but that is a different platform altogether. Agolia docsearch looks like a great idea.

**Comment by jayvdb** [comment]
@yukiisbored , does Sphinx search work without javascript?  If so, we'd need to verify DocSearch degrades gracefully.

**Comment by yukiisbored** [comment]
@jayvdb Actually, i just noticed it won't even show up.

**Comment by jayvdb** [comment]
What "wont even show up" ?; Sphinx or Agolia DocSearch ?

**Comment by yukiisbored** [comment]
Sphinx.

Javascript enabled: https://my.mixtape.moe/jvscjw.png
Javascript disabled: https://my.mixtape.moe/glzimk.png

**Comment by yukiisbored** [comment]
Since I can't find any algolia docsearch instance that uses Sphinx. I'm trying it out on Vue.js and the search box came up but I can't search (The Enter button doesn't work, most likely it's handled in JS instead of a HTML Submission form)

**Comment by meetmangukiya** [comment]
@yukiisbored yes, there is no form submission, it checks if the text in the input box is changed and shows the search results in the dropdown as you type.

**Comment by jayvdb** [comment]
@meetmangukiya , this is finished?

**Comment by meetmangukiya** [comment]
Yes
