### ISSUE TITLE
Rebase bot

### ISSUE THREAD

**Issue by jayvdb** [coala/meta#93]
There are several stable rebase bots in operation. We should deploy one, or integrate functionality into gitmate.

**Comment by sils** [comment]
"… waits for tests and merge automatically when green" that's charming. I want that. If it fastforwards and doesn't merge, if we wanted that we'd have the pypi deployment in a master job instead of in the rultor merge.

**Comment by jayvdb** [comment]
> "… waits for tests and merge automatically when green"

Hmm, the text you are quoting has disappeared from memory.  Perhaps it was in gitter?

Anyway, gitmate now does some of this.  Is it stable and working @sils?
So perhaps we create new issues for related ideas and close this one, or expand the scope & title of this issue.

**Comment by sils** [comment]
- gitmate sets an approval label when everything goes green
- gitmate rebases when being commanded to

**Comment by jayvdb** [comment]
Raised https://gitlab.com/gitmate/GitMate-2-ideas/issues/33
